[module]
  [[module.imports]]
    path = "github.com/martignoni/hugo-notice"
  [[module.imports]]
    path = 'github.com/tomowang/hugo-theme-tailwind'

[markup]
  _merge = "deep"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]
  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[pagination]
  pagerSize = 3

baseURL = "https://cloudclue.blog/"
title = "CloudClue.blog"
description = "CloudClue is a blog covering Cloud Infrastructure, AI and Security topics. It is brought to you by Husam Hilal"
author = "Husam Hilal"
copyright = "Husam Hilal"
languageCode = 'en-us'
defaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "hugo-theme-tailwind"
enableGitInfo = true