# GA Tracking ID
[googleAnalytics]
  ID = "G-1TGCWDDSG6"

[microsoft_clarity]
  id = 'pudemechet'

[instagram]
  disableInlineCSS = true

[twitter]
  disableInlineCSS = true

# comments
[disqus]
# https://gohugo.io/templates/internal/#disqus
# disqusShortname = "your-disqus-shortname"
  shortname = ''