baseURL = 'https://cloudclue.blog/'
languageCode = 'en-us'
title = 'CloudClue.blog'
theme = 'DoIt'

[params]
  # DoIt theme version
  version = "0.3.X"

  # website title
  title = "My New Hugo Site"

  # site description
  description = "This is My New Hugo Site"

  # site keywords
  keywords = ["Theme", "Hugo"]

  # DoIt CHANGED | 0.2.11 site default theme ("light", "dark", "black", "auto")
  defaultTheme = "light"

# - Menu ---------------------------------------------------------------------------------
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
[[menu.main]]
    identifier = "series"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Series"
    url = "/series/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
[[menu.main]]
    identifier = "about"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "About"
    url = "/about/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 3
#  [[menu.main]]
#    identifier = "tags"
#    pre = ""
#    post = ""
#    name = "Tags"
#    url = "/tags/"
#    title = ""
#    weight = 2
#  [[menu.main]]
#    identifier = "categories"
#    pre = ""
#    post = ""
#    name = "Categories"
#    url = "/categories/"
#    title = ""
#    weight = 3

#-------------------------------------------------------#

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
    
  # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # DoIt NEW | 0.2.11 Theme change mode
    # theme change mode ("switch", "select")
    themeChangeMode = "select"
    # DoIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "CloudClue.blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = "🌩️"
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # DoIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = true

  # Footer config
  [params.footer]
    enable = true
    # DoIt NEW | 0.2.0 Custom content (HTML format is supported)
    # custom = 'Husam Hilal'
    # DoIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = false
    # DoIt NEW | 0.2.14 Hosted on (HTML format is supported)
    hostedOn = '<a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>' 
    # DoIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # DoIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2023
    # license info (HTML format is supported)
    #'<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    license = ''

# DoIt NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
    # DoIt NEW | 0.2.13 recently updated posts settings
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10

  # DoIt NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # Home page config
  [params.home]
    # DoIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      # Place your avatar file under static or assets directory
      # The filepath is relative to the static or assets directory
      avatarURL = "/images/avatar.webp"
      # DoIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "Welcome to CloudClue.blog"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # DoIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 9
      # DoIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    GitHub = "husamhilal"
    Linkedin = "husamhilal"
    Youtubechannel = "husamhilal"
    Email = "husamhilal@hotmail.com"
    RSS = true # DoIt NEW | 0.2.0


#-----------------------------------------------------------------------------#

  # DoIt NEW | 0.2.0 Analytics config
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-1TGCWDDSG6"
      # whether to anonymize IP
      anonymizeIP = false

#-----------------------------------------------------------------------------#

# Author config
[author]
  name = "Husam Hilal"
  email = "husamhilal@hotmail.com"
  link = "https://www.husamhilal.com"
  avatar = ""
  gravatarEmail = ""

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy config
[privacy]
  # DoIt DELETED | 0.2.0 privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  # DoIt CHANGED | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

# Options for taxonomies
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"